# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MemoryUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import pymssql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QGraphicsObject
import Const


class MemoryUI(QGraphicsObject):
    def __init__(self):
        super().__init__()
        self.wordlist = list()
        self.TotalMemoNumber = 0
        self.nowMemoNumber = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 584)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 182, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ok_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")
        self.verticalLayout.addWidget(self.ok_btn)
        self.ok_btn.clicked.connect(self.okAction)

        self.info_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.info_btn.setFont(font)
        self.info_btn.setObjectName("info_btn")
        self.verticalLayout.addWidget(self.info_btn)
        self.info_btn.clicked.connect(self.infoShow)

        self.pass_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pass_btn.setFont(font)
        self.pass_btn.setObjectName("pass_btn")
        self.verticalLayout.addWidget(self.pass_btn)
        self.pass_btn.clicked.connect(self.passAction)

        self.miss_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.miss_btn.setFont(font)
        self.miss_btn.setObjectName("miss_btn")
        self.verticalLayout.addWidget(self.miss_btn)
        self.miss_btn.clicked.connect(self.missAction())

        self.back_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout.addWidget(self.back_btn)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.back_btn.clicked.connect(self.back)

        self.LastWord = QtWidgets.QVBoxLayout()
        self.LastWord.setObjectName("LastWord")
        self.lastWord = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.lastWord.setObjectName("lastWord")
        self.LastWord.addWidget(self.lastWord)
        self.LastWordPara = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.LastWordPara.setObjectName("LastWordPara")
        self.LastWord.addWidget(self.LastWordPara)
        self.lastWordSentence = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.lastWordSentence.setObjectName("lastWordSentence")
        self.LastWord.addWidget(self.lastWordSentence)
        self.verticalLayout.addLayout(self.LastWord)

        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(210, 30, 561, 411))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.WordBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_3)
        self.WordBrowser.setObjectName("WordBrowser")
        self.verticalLayout_2.addWidget(self.WordBrowser)
        self.infos = QtWidgets.QTabWidget(self.verticalLayoutWidget_3)
        self.infos.setObjectName("infos")

        self.word = QtWidgets.QWidget()
        self.word.setObjectName("word")
        self.paraEdit = QtWidgets.QTextEdit(self.word)
        self.paraEdit.setGeometry(QtCore.QRect(20, 10, 511, 141))
        self.paraEdit.setObjectName("paraEdit")
        self.infos.addTab(self.word, "")
        self.sentence = QtWidgets.QWidget()
        self.sentence.setObjectName("sentence")
        self.sentence_2 = QtWidgets.QTextEdit(self.sentence)
        self.sentence_2.setGeometry(QtCore.QRect(20, 10, 511, 141))
        self.sentence_2.setObjectName("sentence_2")
        self.infos.addTab(self.sentence, "")
        self.verticalLayout_2.addWidget(self.infos)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 440, 401, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UserName = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.UserName.setFont(font)
        self.UserName.setAlignment(QtCore.Qt.AlignCenter)
        self.UserName.setObjectName("UserName")
        self.horizontalLayout.addWidget(self.UserName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.Icon = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.Icon.setObjectName("Icon")
        self.horizontalLayout.addWidget(self.Icon)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(610, 440, 161, 111))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DayNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.DayNumber.setObjectName("DayNumber")
        self.gridLayout_3.addWidget(self.DayNumber, 0, 1, 1, 1)
        self.UptoNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.UptoNumber.setObjectName("UptoNumber")
        self.gridLayout_3.addWidget(self.UptoNumber, 5, 1, 1, 1)
        self.UptoWords = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.UptoWords.setFont(font)
        self.UptoWords.setAlignment(QtCore.Qt.AlignCenter)
        self.UptoWords.setObjectName("UptoWords")
        self.gridLayout_3.addWidget(self.UptoWords, 5, 0, 1, 1)
        self.WordNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.WordNumber.setObjectName("WordNumber")
        self.gridLayout_3.addWidget(self.WordNumber, 4, 1, 1, 1)
        self.totalDays = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.totalDays.setFont(font)
        self.totalDays.setAlignment(QtCore.Qt.AlignCenter)
        self.totalDays.setObjectName("totalDays")
        self.gridLayout_3.addWidget(self.totalDays, 0, 0, 1, 1)
        self.TotalWords = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.TotalWords.setFont(font)
        self.TotalWords.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalWords.setObjectName("TotalWords")
        self.gridLayout_3.addWidget(self.TotalWords, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.infos.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EnHelper[背诵中.......]"))
        self.ok_btn.setText(_translate("MainWindow", "认        识"))
        self.info_btn.setText(_translate("MainWindow", "查看释义"))
        self.pass_btn.setText(_translate("MainWindow", "直接通过"))
        self.miss_btn.setText(_translate("MainWindow", "计入错题"))
        self.lastWord.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">上一个单词：</p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

        self.LastWordPara.setHtml(_translate("MainWindow",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                             "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">释义：</p></body></html>"))

        self.lastWordSentence.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">例句：</p></body></html>"))

        self.back_btn.setText(_translate("MainWindow", "返回"))
        self.infos.setTabText(self.infos.indexOf(self.word), _translate("MainWindow", "单词释义"))
        self.infos.setTabText(self.infos.indexOf(self.sentence), _translate("MainWindow", "相关例句"))
        self.UserName.setText(_translate("MainWindow", "UserName:" + Const.username_now))

        self.UptoWords.setText(_translate("MainWindow", "剩余单词"))
        self.totalDays.setText(_translate("MainWindow", "坚持天数"))
        self.TotalWords.setText(_translate("MainWindow", "背诵词数"))

        # 获取本次背诵单词列表
        self.WordListLoad()

        # todo
        # 加载头像
        self.Icon.setText(_translate("MainWindow", "Icon"))

    # 加载单词列表
    def WordListLoad(self):
        conn = pymssql.connect(Const.server, Const.user, Const.password, "EnHelper")
        cur = conn.cursor()
        sql = ""
        count = 0
        row = cur.fetchone()
        while row and count <= 50:
            count = count + 1
            self.wordlist.append(row)
        cur.close()
        conn.close()

    # todo
    def missAction(self):
        """
        添加错误记录
        显示单词信息
        :return:
        """
        pass

    # todo
    def okAction(self):
        """
        添加背诵记录
        刷新列表
        :return:
        """
        pass

    # todo
    def infoShow(self):
        """
        显示单词信息
        :return:
        """
        pass

    # todo
    def passAction(self):
        """
        添加背诵记录 但不进行复习测试
        :return:
        """
        pass

    def backAction(self):
        """

        :return:
        """
        pass

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = MemoryUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
