# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MistakeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
import pymssql
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtGui import QStandardItemModel
from PyQt5.QtWidgets import QGraphicsObject, QApplication, QMainWindow, QMessageBox

import Const


class MistakeUI(QMainWindow):
    backSignal = pyqtSignal()

    def __init__(self):
        super().__init__()
        self.mis_list = list()
        self.GetMisslist()
        self.nowcur = 0
        self.length = len(self.mis_list)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 580)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 181, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.test_btn.setFont(font)
        self.test_btn.setObjectName("test_btn")
        self.verticalLayout.addWidget(self.test_btn)
        self.mis_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.mis_btn.setFont(font)
        self.mis_btn.setObjectName("mis_btn")
        self.verticalLayout.addWidget(self.mis_btn)
        self.back_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.back_btn.clicked.connect(self.back)

        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.back_btn.setFont(font)
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout.addWidget(self.back_btn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 30, 551, 521))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.MistakeView = QtWidgets.QTableView(self.verticalLayoutWidget_2)
        self.MistakeView.setObjectName("MistakeView")
        self.verticalLayout_2.addWidget(self.MistakeView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EnHelper[错题]"))
        self.test_btn.setText(_translate("MainWindow", "上一页"))
        self.mis_btn.setText(_translate("MainWindow", "下一页"))
        self.back_btn.setText(_translate("MainWindow", "返回"))

        self.model = QStandardItemModel(10, 5)
        self.WordTable.setModel(self.model)

        for i in range(5):
            self.model.setItem(i,self.mis_list[i])


    def message(self, Q, s, title="Info"):
        msg = QMessageBox(Q)
        msg.setWindowTitle(title)
        msg.setText(s)
        print("output:" + s)
        msg.show()
        msg.buttonClicked.connect(msg.exec_)


    def GetMissList(self):
        conn = pymssql.connect(Const.server, Const.user, Const.password, "EnHelper")
        cur = conn.cursor()
        sql = "select * from UserMistake where ID = '{}'".format(Const.userid_now)
        cur.execute(sql)
        row = cur.fetchone()
        while row is not None:
            self.mis_list.append(row)
            row = cur.fetchone()
        cur.close()
        conn.close()
        print(self.mis_list)


    def up(self):
        pass

    def down(self):
        pass

    def back(self):
        self.backSiganl.emit()
        print("backSignal")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = MistakeUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
