# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MemoryUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# Author:Tengfei_Sakurie
#
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import pymssql
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtGui import QStandardItemModel
from PyQt5.QtWidgets import QGraphicsObject, QApplication, QMainWindow, QAbstractItemView
import Const

# 常量定义
server = "127.0.0.1"
password = "qwer"
user = "usr"

class MainUI(QGraphicsObject):
    memo_signal = pyqtSignal()
    test_signal = pyqtSignal()
    set_signal = pyqtSignal()
    sear_signal = pyqtSignal()
    mistake_signal = pyqtSignal()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 580)
        MainWindow.setMinimumSize(QtCore.QSize(800, 580))
        MainWindow.setMaximumSize(QtCore.QSize(800, 580))
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 130, 561, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.WordTable = QtWidgets.QTableView(self.gridLayoutWidget)
        self.WordTable.setObjectName("WordTable")
        self.WordTable.setEditTriggers(QAbstractItemView.NoEditTriggers)

        self.gridLayout.addWidget(self.WordTable, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 181, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.Icon = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Icon.setAlignment(QtCore.Qt.AlignCenter)
        self.Icon.setObjectName("Icon")
        self.verticalLayout.addWidget(self.Icon)

        self.UserName = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        self.UserName.setFont(font)
        self.UserName.setAlignment(QtCore.Qt.AlignCenter)
        self.UserName.setObjectName("UserName")
        self.verticalLayout.addWidget(self.UserName)

        self.memo_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.memo_btn.setFont(font)
        self.memo_btn.setObjectName("memo_btn")
        self.verticalLayout.addWidget(self.memo_btn)
        # todo
        self.memo_btn.clicked.connect(self.memo)

        self.sear_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.sear_btn.setFont(font)
        self.sear_btn.setObjectName("sear_btn")
        self.verticalLayout.addWidget(self.sear_btn)
        # todo
        self.sear_btn.clicked.connect(self.sear)

        self.test_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.test_btn.setFont(font)
        self.test_btn.setObjectName("test_btn")
        self.verticalLayout.addWidget(self.test_btn)
        # todo
        self.test_btn.clicked.connect(self.test)

        self.mis_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.mis_btn.setFont(font)
        self.mis_btn.setObjectName("mis_btn")
        self.verticalLayout.addWidget(self.mis_btn)
        # todo
        self.mis_btn.clicked.connect(self.mis)

        self.set_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.set_btn.setFont(font)
        self.set_btn.setObjectName("set_btn")
        self.verticalLayout.addWidget(self.set_btn)
        # todo
        self.set_btn.clicked.connect(self.set)

        self.produced = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.produced.setFont(font)
        self.produced.setAlignment(QtCore.Qt.AlignCenter)
        self.produced.setObjectName("produced")
        self.verticalLayout.addWidget(self.produced)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 30, 401, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.banner = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.banner.setObjectName("banner")
        self.horizontalLayout.addWidget(self.banner)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(610, 30, 160, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.DayssNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.DayssNumber.setObjectName("DayssNumber")
        self.gridLayout_3.addWidget(self.DayssNumber, 2, 1, 1, 1)
        self.WordNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.WordNumber.setObjectName("WordNumber")
        self.gridLayout_3.addWidget(self.WordNumber, 1, 1, 1, 1)
        self.DayNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.DayNumber.setObjectName("DayNumber")
        self.gridLayout_3.addWidget(self.DayNumber, 0, 1, 1, 1)
        self.totalDays = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.totalDays.setFont(font)
        self.totalDays.setObjectName("totalDays")
        self.gridLayout_3.addWidget(self.totalDays, 0, 0, 1, 1)
        self.TotalWords = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.TotalWords.setFont(font)
        self.TotalWords.setObjectName("TotalWords")
        self.gridLayout_3.addWidget(self.TotalWords, 1, 0, 1, 1)
        self.DaysDays = QtWidgets.QLabel(self.gridLayoutWidget_2)

        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.DaysDays.setFont(font)
        self.DaysDays.setObjectName("DaysDays")
        self.gridLayout_3.addWidget(self.DaysDays, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Icon.setText(_translate("MainWindow", "Icon"))
        #self.UserName.setText(_translate("MainWindow", "UserName:XXXXXX"))
        self.memo_btn.setText(_translate("MainWindow", "单词背诵"))
        self.sear_btn.setText(_translate("MainWindow", "单词查询"))
        self.test_btn.setText(_translate("MainWindow", "单词测试"))
        self.mis_btn.setText(_translate("MainWindow", "笔记&错题"))
        self.set_btn.setText(_translate("MainWindow", "设置"))
        self.produced.setText(_translate("MainWindow", "Produced by SakuRie"))
        self.banner.setText(_translate("MainWindow", "Banner is here"))
        self.totalDays.setText(_translate("MainWindow", "坚持天数"))
        self.TotalWords.setText(_translate("MainWindow", "背诵词数"))
        self.DaysDays.setText(_translate("MainWindow", "连续天数"))
        # 修改展示信息 连接数据库
        conn = pymssql.connect(server, user, password, "EnHelper")
        cur = conn.cursor()
        sql = "select ID,UserName from Users"
        cur.execute(sql)
        row = cur.fetchone()
        id = row[0]
        name = row[1]
        while row:
            if id == Const.userid_now:
                self.UserName.setText("UserName:" + name)
                break
            row = cur.fetchone()
            id = row[0]
            name = row[1]
        cur.close()
        # 表格
        cur = conn.cursor()
        sql = "select Word from UserMemory"
        cur.execute(sql)
        self.model = QStandardItemModel(10,5)
        self.WordTable.setModel(self.model)
        row = cur.fetchone()
        rownum = 1
        while row:
            for i in range(5):
                self.model.setItem(rownum,i,row[i])
            row = cur.fetchone()
            rownum = rownum+1
        cur.close()
        #done

        # todo
        # 用户数据显示
        cur = conn.cursor()
        sql = ""
        cur.close()
        self.DayNumber.display(10)
        self.DayssNumber.display(7)
        self.WordNumber.display(1024)
        # done


    def mis(self):
        self.mistake_signal.emit()
        print("mistake_signal")

    def memo(self):
        self.memo_signal.emit()
        print("memo_signal")

    def test(self):
        self.test_signal.emit()
        print("test_signal")

    def sear(self):
        self.sear_signal.emit()
        print("sear_signal")

    def set(self):
        self.set_signal.emit()
        print("set_signal")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = MainUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
